<?php

namespace Holgerk\AssertGolden;

use PHPUnit\Framework\Assert;
use Symfony\Component\VarExporter\VarExporter;

$index = array_search('--update-golden', $_SERVER['argv'], true);
if ($index !== false) {
    Insertion::$forceUpdateGolden = true;

    // remove argument / hide it from phpunit bootstrap
    array_splice($_SERVER['argv'], $index, 1);
}

/**
 * Same as `assertEquals`, but when `null` is given as argument, the test file is automatically edited and `null`
 * is substituted with the actual value
 */
function assertGolden(mixed $expected, mixed $actual, string $message = ''): void
{
    _internalAssertGolden($expected, $actual, $message);
}

function assertGoldenFile(mixed $actual, string $message = ''): void
{
    _internalAssertGoldenFile($actual, $message);
}

/** @internal */
function _internalAssertGolden(mixed $expected, mixed $actual, string $message = ''): void
{
    if ($expected === null || Insertion::$forceUpdateGolden) {
        $expected = $actual;
        Insertion::register(VarExporter::export($actual));
    }

    Assert::assertEquals($expected, $actual, $message);
}

/** @internal  */
function _internalAssertGoldenFile(mixed $actual, string $message = ''): void
{
    $trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 3);
    $testFile = $trace[1]['file'];
    $testFunction = $trace[2]['function'];
    $pathinfo = pathinfo($testFile);
    $goldenFile = $pathinfo['dirname'] . '/' . $pathinfo['filename'] . '_' . $testFunction . '.golden.php';
    if (!file_exists($goldenFile) || Insertion::$forceUpdateGolden) {
        $exported = VarExporter::export($actual);
        file_put_contents($goldenFile, <<<EOF
            <?php
            // DO NOT EDIT (autogenerated by assertGoldenFile)
            
            return $exported;
            EOF
        );
        echo "\nassertGoldenFile | created: $goldenFile\n";
    }
    $expected = include $goldenFile;
    Assert::assertEquals($expected, $actual, $message);
}